# .github/workflows/test-sqlite.yml
name: Tests with SQLite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [11.*, 12.*]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} (SQLite)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml, ctype, iconv, intl, sqlite, pdo_sqlite
        coverage: none

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-interaction
        composer update --prefer-dist --no-interaction --no-progress

    - name: Execute tests
      run: vendor/bin/phpunit
